### ISSUE TITLE
Causing Crashes due to Compatibility Conflict w/ Macaw's Bridges 3.0.0 

### ISSUE THREAD

**Issue by Kschermers** [Samlegamer/Macaw-s-Bridges-Compat#27]
Macaw's Bridges newly released 3.0.0 version causes this mod to crash the Minecraft client on launch.
Macaw's Bridges BOP Version: 1.1
Game Version: 1.20.1
Forge Version:  47.2.0

**Comment by 5pHiNxX** [comment]
same here, Stacktrace:

`Mod File: /C:/Users/5pHiNxX/curseforge/minecraft/Instances/SpHiNxX's Technical Overhaul (2)/mods/macawsbridgesbop-1.20-1.1.jar
	Failure message: Macaw's Bridges - BOP (macawsbridgesbop) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.20-1.1
	Mod Issue URL: https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues
	Exception message: java.lang.ClassNotFoundException: com.mcwbridges.kikoz.objects.Support_Pillar
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at fr.samlegamer.macawsbridgesbop.MacawsBridgesBOP.<init>(MacawsBridgesBOP.java:29) ~[macawsbridgesbop-1.20-1.1.jar%23493!/:1.20-1.1] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.2.0.jar%23598!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.0.jar%23597!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}`

**Comment by Lord-Greyhawk** [comment]
Been having similar issues. I went to the creators of the regular Bridges version and have had a few other conflicts with BOP working with Bridges 3.0 when this one is not active. It refuses to load if this mods is active.

**Comment by Samlegamer** [comment]
Updated in 1.20-1.2

**Comment by Lord-Greyhawk** [comment]
Running 1.20.4 on the Fabric loader 0.15.9 and had the peoblems only 2 days ago

**Comment by Kschermers** [comment]
This issue has been fixed for Forge version with new 1.2 release. @Lord-Greyhawk the update was released more recently than that, please confirm if you are able to update the mod.
